development:
  adapter: postgresql
  username: postgres
  password: postgres
  database: circuitverse_development
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 5432